name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch: # Enables the manual browser UI button

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            asmithadq/online-assessment:v1
            asmithadq/online-assessment:latest
      
      - name: Verify secrets
        run: |
          echo "Host length: ${#HOST}"
          echo "Port: $PORT"
          echo "User: $USER"
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          PORT: ${{ secrets.SERVER_PORT }}
          USER: ${{ secrets.SERVER_USER }}

      - name: Network diagnostics
        run: |
          echo "Host: ${{ secrets.SERVER_HOST }}"
          nslookup ${{ secrets.SERVER_HOST }} || true
          ping -c 3 ${{ secrets.SERVER_HOST }} || true
          nc -vz ${{ secrets.SERVER_HOST }} ${{ secrets.SERVER_PORT }} || true    
      
      - name: Test SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 120s
          command_timeout: 120s
          debug: true
          script: |
            echo "Connected"
            hostname
            whoami
      
      - name: Print Secret Lengths
        run: |
          echo "HOST LENGTH: ${#SERVER_HOST}"
          echo "PORT LENGTH: ${#SERVER_PORT}"
          echo "USER LENGTH: ${#SERVER_USER}"
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
      
      
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          debug: true
          script: |
            cd /opt/arima/data/stacks/online-assessment
            docker compose pull
            docker compose up -d
